### ISSUE TITLE
ms-setup.pl: virtualbox uses eth0

### ISSUE THREAD

**Issue by utdrmac** [grypyrg/vagrant-percona#19]
Attempting to use ms-setup.pl. All latest versions of Virtualbox and vagrant. Script could not find ip address of master because script was looking for eth1's ip.

Use of ~~ (smart match) is considered experimental so you may want something different as solution.

```
diff --git a/ms-setup.pl b/ms-setup.pl
index 9bcb4dd..62cebba 100755
--- a/ms-setup.pl
+++ b/ms-setup.pl
@@ -18,7 +18,7 @@ foreach my $line( @running_nodes_lines ) {
 # Harvest node ips
 foreach my $node( @running_nodes ) {
        my $nic = 'eth1';
-       $nic = 'eth0' if $node->{provider} eq 'aws';
+       $nic = 'eth0' if $node->{provider} ~~ ('aws', 'virtualbox');
```

**Comment by grypyrg** [comment]
send a PR and I will merge it.

**Comment by utdrmac** [comment]
no PRs for 1-liners :-P

**Comment by grypyrg** [comment]
I'm sorry, but if you want to get this fixed, I expect you to send a PR. Don't put the work on me.

**Comment by utdrmac** [comment]
i gave you the fix above

**Comment by grypyrg** [comment]
I don't have a problem, I don't need anything fixed.

Send a PR so I can merge this fix.
