### ISSUE TITLE
run_sysbench_reload.sh fails on duplicate table

### ISSUE THREAD

**Issue by utdrmac** [grypyrg/vagrant-percona#21]
I'm trying to debug this one now. Can't figure out why it's trying to create the table twice.

```
[root@master ~]# /usr/local/bin/run_sysbench_reload.sh
sysbench 0.5:  multi-threaded system evaluation benchmark

Dropping table 'sbtest1'...
sysbench 0.5:  multi-threaded system evaluation benchmark

Running the test with following options:
Number of threads: 1
Random number generator seed is 0 and will be ignored


Initializing worker threads...

Threads started!

thread prepare0
Creating table 'sbtest1'...
Inserting 100000 records into 'sbtest1'
BEFORE DONE
thread prepare0
Creating table 'sbtest1'...
ALERT: mysql_drv_query() returned error 1050 (Table 'sbtest1' already exists) for query 'CREATE TABLE sbtest1 (
id INTEGER UNSIGNED NOT NULL ,
k INTEGER UNSIGNED DEFAULT '0' NOT NULL,
c CHAR(120) DEFAULT '' NOT NULL,
pad CHAR(60) DEFAULT '' NOT NULL,
PRIMARY KEY (id)
) /*! ENGINE = innodb MAX_ROWS = 1000000 */ '
FATAL: failed to execute function `event': 3
```

**Comment by grypyrg** [comment]
it's stuff I don't use anyway, like much of the code in this repo.

**Comment by utdrmac** [comment]
So, you aren't using this repo at all then? You aren't maintaining it anymore? If not, that's ok, I'll request IT clone it under Percona-Lab like Jay suggested. And I'll work on cloning your vagrant images under Percona's account as well.

**Comment by grypyrg** [comment]
I am still using the repo, but much of the code is legacy and not used anymore, such as the `run_sysbench_reload.sh` you mentioned.

**Comment by grypyrg** [comment]
I don't know what your problem is @utdrmac, Forking and sending a PR is the most normal thing to do in GitHub... It's the whole point of Git/GitHub.

**Comment by utdrmac** [comment]
I just think it is the absolute dumbest thing about git/github; requiring such an intensive step to simply make a 4 character change. It has nothing to do with you or this repo. It's my issue with git overall.

**Comment by grypyrg** [comment]
As suggested, consider making the change of a file in a repo by clicking the `Edit` button on GitHub. It will automatically create a fork and make a PR request, all in 1 click...

**Comment by grypyrg** [comment]
Keep in mind that this platform is github. whether you like it or not... If you don't want to work the github way, don't expect me to do the work for you.
