### ISSUE TITLE
No custom IPs work with vitrualbox

### ISSUE THREAD

**Issue by utdrmac** [grypyrg/vagrant-percona#26]
I'm not sure if this is a config setting within Virtualbox itself or an issue with the image. Many of the Vagrantfile.* files have private IP settings but none take affect.

In every test case (over 40 by this point) I've done, eth0 always gets 10.0.2.15. And unless `type: 'dhcp'` is given, eth1 will not be created.

From what I've read, virtualbox's ip settings are based on the interface's MAC address. I've noticed that in every test case the MAC address of eth0 is always the same, 08:00:27:89:cd:2e. This is what makes me think it's an issue with the image.

Not sure if this is something to be worried about as using the dhcp option above has allowed every Vagrantfile I've tested to work just fine. eth0 becomes a NAT'd bridge to my laptop for external internet and eth1 handles vm-to-vm communications.

**Comment by grypyrg** [comment]
`eth0` always gets `10.0.2.15` by vagrant/virtualbox as it's the `nat` adaptor. 
`eth1` is always used to make a bridge or internal net. example:
```
node_config.vm.network :private_network, ip: node_params['local_vm_ip'], adaptor: if_adapter
```

**Comment by utdrmac** [comment]
I tried exactly what you put above and set if_adapter='vboxnet1' but the interface doesn't seem to start up. I have to manually run `ifup eth1` and then it appears with the IP as set in Vagrantfile.

**Comment by utdrmac** [comment]
Might be a bug: https://github.com/mitchellh/vagrant/issues/8166

**Comment by utdrmac** [comment]
Yep, it's a bug that was recently introduced. https://github.com/mitchellh/vagrant/issues/8142
Doesn't affect vagrant 1.9.0 and I'm on 1.9.2

**Comment by grypyrg** [comment]
Great. thanks for the research!

**Comment by utdrmac** [comment]
and that fixed it. I applied these manually (https://github.com/mitchellh/vagrant/pull/8148/files) and the interface comes up now. geezum.
